id_list = [20115, 20116, 20114, 20113, 20112, 20109, 20108, 20101, 20100, 20099, 20098, 20095, 20094, 20093, 20089, 20088, 20086, 20084, 20083, 20082, 20080, 20079, 20078, 20077, 20075, 20071, 20070, 20068, 20067, 20066, 20065, 20064, 20063, 20062, 20060, 20059, 20052, 20051, 20050, 20049, 20047, 20046, 20045, 20044, 20042, 20041, 20038, 20037, 20036, 20033, 20028, 20027, 20023, 20022, 20021, 20020, 20019, 20017, 20016, 20015, 20014, 20013, 20010, 20009, 20008, 20005, 20004, 20003, 20002, 20000, 19999, 19997, 19996, 19994, 19986, 19985, 19984, 19983, 19982, 19980, 19978, 19976, 19975, 19970, 19965, 19962, 19961, 19960, 19958, 19956, 19953, 19952]

client_list = [ "JAPA VIDROS", "BOTARO", "MONTE CASTELO  VIDROS - ANDERSON", "VR DISTRIBUIDOR - VITOR", "JORGE UTILITY", "MULTIVIDROS THAISE", "FAGUNDES AMBIENTES PLANEJADOS", "JAPA VIDROS", "MOVEIS PLAN RAFAEL ", "2 OU MAIS MOVEIS PLANEJADOS ", "B E B MOVEIS PLANEJADO", "O MARCENEIRO PLANEJADOS VANESSA ", "JOHN", "CAVALCANTE", "2M MOVELARIA", "JAPA VIDROS", "VALE MODELLY - KELLY CRISTINA", "BENEVAL ", "MARFIM MOVELARIA", "JULIA NASCIMENTO CORREIA LIMA", "LA CASA AMBIENTES PLANEJADOS", "LA CASA AMBIENTES PLANEJADOS", "JUNIOR FOX", "FILIPE FERNANDES", "MARCELO DE MORAIS", "ADAQUIEL VIDROS", "ATILA MOVELARIA ", " VEZZANO MOVEIS E DESIGN", "VALE MODELLY - KELLY CRISTINA", "ALFA MOVELARIA", "WALMIR PIRES E ALMEIDA", "PERFIL 10", "MARCENARIA TAUBATÉ ", "D MOVEL DESIG", "CAVALCANTE", "PEDRO HENRIQUE LEME", "IMPACTTO MOVELARIA", "LION VIDROS", "MC MIQUEIAS ", "MARFIM MOVELARIA", "REAL BOX", "HS STEEL ", "WA MOVELARIA", "JORGE UTILITY", "D MOVEL DESIG", "2M MOVELARIA", "EVERALDO", "MULTIVIDROS THAISE", "RENOVA COMERCIO DE VIDROS", "GIGANTE MOVELARIA ", "PERFIL 10", "MARCENARIA TAUBATÉ ", " VEZZANO MOVEIS E DESIGN", "MARFIM MOVELARIA", "MARCENARIA TAUBATÉ ", "MARCENARIA TAUBATÉ ", "MARCENARIA TAUBATÉ ", "MARCENARIA TAUBATÉ ", "DM INTERIORES MARCENARIA ALTO PADRAO", "MDA MOVELARIA E COMERCIO DE MOVEIS EIRELI ", "CONSUMIDOR FINAL ", "COMERCIAL ANDRADE MAT CONSTRUÇÃO", "TEMPER MINAS-", "FAGUNDES AMBIENTES PLANEJADOS", "CAVALCANTE", "MODELAR MOVEIS PLANEJADOS", "TOCO MARCENERIA ", "TOCO MARCENERIA ", "JOEL RONCOLETTA MARCENEIRO", "BENEVAL ", "RESTART PLANEJADOS ", "BENEVAL ", "MC MIQUEIAS ", "ESQUALY VALE", "AUTENTIC MOVELARIA", "BENEVAL ", "VR DISTRIBUIDOR - VITOR", "FAGUNDES AMBIENTES PLANEJADOS", "FAGUNDES AMBIENTES PLANEJADOS", "ESQUALY VALE", "JAPA VIDROS", "VITRIFER A CASA DO VIDRACEIRO ", "IVO ", "CÁSSIO TAUBATÉ ", "LEANDRO BALCÃO", "IN VITRO SOLUCOES EM VIDROS.", "ESQUALY VALE", "LUGANNO ESQUADRIAS DE ALUMINIO LTDA", "ALEX BERNADI ", "PAULO CAÇAPAVA ", "LEY VEIGA", "BUIA STILO", ]

est_prod = [ "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "PRODUÇÃO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "RETIRADO", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "EXPEDIÇÃO - ENTREGA", "EXPEDIÇÃO - ENTREGA", "EXPEDIÇÃO - RETIRA", "EXPEDIÇÃO - RETIRA", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "EXPEDIÇÃO - RETIRA", "PRODUÇÃO", "RETIRADO", "EXPEDIÇÃO - ENTREGA", "PRODUÇÃO", "PRODUÇÃO", "RETIRADO", "EXPEDIÇÃO - ENTREGA", "EXPEDIÇÃO - ENTREGA", "RETIRADO", "RETIRADO", "", "PRODUÇÃO", "EXPEDIÇÃO - ENTREGA", "EXPEDIÇÃO - ENTREGA", "PRODUÇÃO", "PRODUÇÃO", "PRODUÇÃO", "EXPEDIÇÃO - RETIRA", "RETIRADO", ]

# data = {id_list:id_list, client_list:client_list, est_prod:est_prod}

def criar_query_insercao(arr_id, arr_name, arr_est, tabela):
    # arr_id = data.id_list
    # arr_name = data.client_list
    # arr_est = data.est_prod

    if len(arr_id) != len(arr_name) or len(arr_id) != len(arr_est):
        raise ValueError("Os arrays devem ter o mesmo tamanho.")
    
    valores = []
    
    for i in range(len(arr_id)):
        id = arr_id[i]
        client = arr_name[i]
        estage = arr_est[i]
        if estage == 'PRODUÇÃO' or estage == '':
            is_ready = False
            destiny = 'Não informado'
        elif estage == 'EXPEDIÇÃO - ENTREGA':
            is_ready = True
            destiny = 'Entrega'
        elif estage == 'EXPEDIÇÃO - RETIRA':
            is_ready = True
            destiny = 'Retira'
        else:
            is_ready = True
        
        valores.append(f"('{id}', '{client}', '{is_ready}', '{destiny}')")

    query = f"INSERT INTO {tabela} (id, client, is_ready, destiny) VALUES {', '.join(valores)};"
    
    return query

print(criar_query_insercao(id_list,client_list,est_prod, 'order_order'))