# Generated by Django 4.2.2 on 2023-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(default='não especificado', max_length=100)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
