# Generated by Django 4.2.2 on 2023-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destiny',
            field=models.CharField(choices=[('retira', 'Retira'), ('entrega', 'Entrega'), ('retira-entrega', 'Retira-Entrega')], default='retira', max_length=15),
        ),
    ]
