# Generated by Django 4.2.2 on 2023-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_date_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estage',
            field=models.CharField(default='Produção'),
        ),
    ]
